---
- apt: pkg=logrotate

- template: >
    src=logrotate.conf.j2
    dest={{ logrotate_config_dir }}/{{ logrotate_name }}
    mode=0644
    group=root
    owner=root
  when: logrotate_name is defined

- name: validate config
  shell: logrotate --debug {{ logrotate_config_dir }}/{{ logrotate_name }}
  when: logrotate_name is defined
