---
- shell: dpkg -l logrotate
  register: install_result

- name: ensure logrotate package is installed
  assert:
    that:
      - "{{ install_result.rc }} == 0"

- shell: stat -c %a /etc/logrotate.d/test_log
  register: stat_result
- name: ensure logrotate config modes
  assert:
    that:
      - "stat_result.stdout == '644'"

- shell: stat -c %U /etc/logrotate.d/test_log
  register: stat_result
- name: ensure logrotate config owner
  assert:
    that:
      - "stat_result.stdout == 'root'"

- shell: stat -c %G /etc/logrotate.d/test_log
  register: stat_result
- name: ensure logrotate config group
  assert:
    that:
      - "stat_result.stdout == 'root'"

- shell: grep -F '/var/log/test.log' /etc/logrotate.d/test_log
  register: grep_result
- name: ensure logrotate config rotates the proper log
  assert:
    that:
      - "grep_result.rc == 0"

- shell: grep daily /etc/logrotate.d/test_log
  register: grep_result
- name: ensure logrotate config has proper frequency directive
  assert:
    that:
      - "grep_result.rc == 0"

- shell: grep -F 'rotate 8' /etc/logrotate.d/test_log
  register: grep_result
- name: ensure logrotate config has proper rotate directive
  assert:
    that:
      - "grep_result.rc == 0"

- shell: grep -F 'create 644 root adm' /etc/logrotate.d/test_conditional_log
  register: grep_result
- name: ensure logrotate config has proper create directive
  assert:
    that:
      - "grep_result.rc == 0"

- shell: awk '/postrotate/, /endscript/' /etc/logrotate.d/test_conditional_log | grep -F 'exec script'
  register: grep_result
- name: ensure logrotate config has proper postrotate directive
  assert:
    that:
      - "grep_result.rc == 0"
