---
- hosts: logrotate
  gather_facts: False
  pre_tasks:
    - apt: update_cache=yes cache_valid_time=21600 # 60 * 60 * 6
  roles:
    - logrotate
  tasks:
    - logrotate: name=test_log path=/var/log/test.log
    - logrotate: >
        name=test_conditional_log
        path=/var/log/test_conditional.log
        create="644 root adm"
        postrotate="exec script"
    - include: roles/logrotate/tasks/test.yml
