---
- hosts: all
  tasks:
    - name: Create a test logrotate config file
      logrotate: name=test
                 path=/var/log/test.log
      args:
        options:
          - daily
          - rotate 8
        scripts:
          postrotate: exec script

    - name: Create a test logrotate config file to delete
      logrotate: name=missing
                 path=/var/log/missing.log
      changed_when: false

    - name: Stat path to test logrotate conf
      stat: path=/etc/logrotate.d/test
      register: logrotate_stat
    - name: Assert that test logrotate conf exists
      assert:
        that:
          - "logrotate_stat.stat.exists == True"

    - name: Remove the test logrotate config file
      logrotate: name=missing
                 path=/var/log/missing.log
                 state=absent
      changed_when: false

    - name: Rotate list of files with default options
      logrotate: name=test_multi
      args:
        path:
          - /var/log/log1.log
          - /var/log/log2.log
